### ISSUE TITLE
npm i throws error

### ISSUE THREAD

**Issue by sakarie9** [magicdawn/node-mozjpeg#5]
`npm i -S node-mozjpeg`

```
npm ERR! code 1
npm ERR! path /tmpfs/node_modules/node-mozjpeg
npm ERR! command failed
npm ERR! command sh -c prebuild-install --runtime=napi || npm run build-native
npm ERR! > node-mozjpeg@1.0.1 build-native
npm ERR! > node install/build-dep.js && node-gyp rebuild
npm ERR! 
npm ERR! [exec]: npx napa
npm ERR! [build unix]
npm ERR! [exec]: autoreconf -fiv
npm ERR! libtoolize: putting auxiliary files in '.'.
npm ERR! libtoolize: copying file './ltmain.sh'
npm ERR! libtoolize: Consider adding 'AC_CONFIG_MACRO_DIRS([m4])' to configure.ac,
npm ERR! libtoolize: and rerunning libtoolize and aclocal.
npm ERR! libtoolize: Consider adding '-I m4' to ACLOCAL_AMFLAGS in Makefile.am.
npm ERR! prebuild-install warn install No prebuilt binaries found (target=3 runtime=napi arch=x64 libc= platform=linux)
npm ERR! info cache https://github.com/mozilla/mozjpeg/archive/v3.3.1.tar.gz into mozjpeg-src
npm ERR! autoreconf: export WARNINGS=
npm ERR! autoreconf: Entering directory '.'
npm ERR! autoreconf: configure.ac: not using Gettext
npm ERR! autoreconf: running: aclocal --force 
npm ERR! autoreconf: configure.ac: tracing
npm ERR! autoreconf: running: libtoolize --copy --force
npm ERR! autoreconf: configure.ac: not using Intltool
npm ERR! autoreconf: configure.ac: not using Gtkdoc
npm ERR! autoreconf: running: aclocal --force 
npm ERR! autoreconf: running: /usr/bin/autoconf --force
npm ERR! configure.ac:23: warning: The macro `AC_PROG_LIBTOOL' is obsolete.
npm ERR! configure.ac:23: You should run autoupdate.
npm ERR! aclocal.m4:122: AC_PROG_LIBTOOL is expanded from...
npm ERR! configure.ac:23: the top level
npm ERR! configure.ac:84: warning: The macro `AC_TRY_COMPILE' is obsolete.
npm ERR! configure.ac:84: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
npm ERR! configure.ac:84: the top level
npm ERR! configure.ac:115: warning: The macro `AC_HEADER_STDC' is obsolete.
npm ERR! configure.ac:115: You should run autoupdate.
npm ERR! ./lib/autoconf/headers.m4:704: AC_HEADER_STDC is expanded from...
npm ERR! configure.ac:115: the top level
npm ERR! configure.ac:128: warning: The macro `AC_TRY_RUN' is obsolete.
npm ERR! configure.ac:128: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:2997: AC_TRY_RUN is expanded from...
npm ERR! configure.ac:128: the top level
npm ERR! configure.ac:164: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:164: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:164: the top level
npm ERR! configure.ac:167: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:167: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:167: the top level
npm ERR! configure.ac:210: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:210: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:210: the top level
npm ERR! configure.ac:291: warning: The macro `AC_TRY_COMPILE' is obsolete.
npm ERR! configure.ac:291: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
npm ERR! configure.ac:291: the top level
npm ERR! configure.ac:289: warning: The macro `AC_TRY_COMPILE' is obsolete.
npm ERR! configure.ac:289: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
npm ERR! configure.ac:289: the top level
npm ERR! configure.ac:287: warning: The macro `AC_TRY_COMPILE' is obsolete.
npm ERR! configure.ac:287: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
npm ERR! configure.ac:287: the top level
npm ERR! configure.ac:285: warning: The macro `AC_TRY_COMPILE' is obsolete.
npm ERR! configure.ac:285: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
npm ERR! configure.ac:285: the top level
npm ERR! configure.ac:299: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:299: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:299: the top level
npm ERR! configure.ac:318: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:318: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:318: the top level
npm ERR! configure.ac:341: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:341: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:341: the top level
npm ERR! configure.ac:353: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:353: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:353: the top level
npm ERR! configure.ac:388: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:388: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:388: the top level
npm ERR! configure.ac:433: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:433: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:433: the top level
npm ERR! configure.ac:449: warning: The macro `AC_HELP_STRING' is obsolete.
npm ERR! configure.ac:449: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
npm ERR! configure.ac:449: the top level
npm ERR! configure.ac:463: warning: The macro `AC_FD_CC' is obsolete.
npm ERR! configure.ac:463: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:399: AC_FD_CC is expanded from...
npm ERR! acinclude.m4:4: AC_PROG_NASM is expanded from...
npm ERR! configure.ac:463: the top level
npm ERR! configure.ac:468: warning: The macro `AC_FD_CC' is obsolete.
npm ERR! configure.ac:468: You should run autoupdate.
npm ERR! ./lib/autoconf/general.m4:399: AC_FD_CC is expanded from...
npm ERR! acinclude.m4:4: AC_PROG_NASM is expanded from...
npm ERR! configure.ac:468: the top level
npm ERR! autoreconf: running: /usr/bin/autoheader --force
npm ERR! autoreconf: running: automake --add-missing --copy --force-missing
npm ERR! configure.ac:18: installing './ar-lib'
npm ERR! configure.ac:16: installing './compile'
npm ERR! configure.ac:23: installing './config.guess'
npm ERR! configure.ac:23: installing './config.sub'
npm ERR! configure.ac:8: installing './install-sh'
npm ERR! configure.ac:8: installing './missing'
npm ERR! configure.ac:599: error: required file 'jconfig.h.in' not found
npm ERR! configure.ac:600: error: required file 'jconfigint.h.in' not found
npm ERR! configure.ac:601: error: required file 'release/mozjpeg.spec.in' not found
npm ERR! configure.ac:602: error: required file 'release/makecygwinpkg.in' not found
npm ERR! configure.ac:603: error: required file 'release/makedpkg.in' not found
npm ERR! configure.ac:604: error: required file 'release/makemacpkg.in' not found
npm ERR! configure.ac:605: error: required file 'release/uninstall.in' not found
npm ERR! configure.ac:606: error: required file 'release/libjpeg.pc.in' not found
npm ERR! configure.ac:607: error: required file 'release/libturbojpeg.pc.in' not found
npm ERR! configure.ac:609: error: required file 'tjbenchtest.in' not found
npm ERR! configure.ac:612: error: required file 'tjbenchtest.java.in' not found
npm ERR! configure.ac:613: error: required file 'tjexampletest.in' not found
npm ERR! configure.ac:615: error: required file 'libjpeg.map.in' not found
npm ERR! configure.ac:616: error: required file 'simd/Makefile.in' not found
npm ERR! configure.ac:617: error: required file 'java/Makefile.in' not found
npm ERR! configure.ac:618: error: required file 'md5/Makefile.in' not found
npm ERR! Makefile.am: installing './depcomp'
npm ERR! Makefile.am:45: error: required directory ./java does not exist
npm ERR! Makefile.am:81: error: required directory ./simd does not exist
npm ERR! Makefile.am:45: error: required directory ./md5 does not exist
npm ERR! autoreconf: error: automake failed with exit status: 1
npm ERR! node:child_process:960
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: Command failed: autoreconf -fiv
npm ERR!     at checkExecSyncError (node:child_process:885:11)
npm ERR!     at execSync (node:child_process:957:15)
npm ERR!     at exec (/tmpfs/node_modules/node-mozjpeg/install/build-dep.js:23:3)
npm ERR!     at buildUnix (/tmpfs/node_modules/node-mozjpeg/install/build-dep.js:73:3)
npm ERR!     at Object.<anonymous> (/tmpfs/node_modules/node-mozjpeg/install/build-dep.js:46:3)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1256:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1119:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:960:12) {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [ null, null, null ],
npm ERR!   pid: 185844,
npm ERR!   stdout: null,
npm ERR!   stderr: null
npm ERR! }
npm ERR! 
npm ERR! Node.js v18.17.1
```

**Comment by sakarie9** [comment]
It's an error caused by corrupted mozjpeg cache file downloaded by napa, related to https://github.com/shama/napa/issues/83

should consider using other package to download github packages since napa is unmaintained in six years
